###GET PurchaseOrder with poNumber
GET localhost:8081/api/purchaseOrders/testpoNumber

###GET all PurchaseOrders
GET localhost:8081/api/purchaseOrders

###POST new order
POST http://localhost:8081/api/purchaseOrders
Content-Type: application/json

{
  "poNumber": "testpoNumber",
  "buyerName": "buyer",
  "buyerAddress": "test address buyer",
  "sellerName": "seller",
  "sellerAddress": "test address seller",
  "date": "2024-09-29T00:00:00",
  "orderLines": [
    {
      "amount": 50,
      "materialName": "GIPS"

    },
    {
      "amount": 0.01,
      "materialName": "IJZERERTS"
    }
  ]
}
